apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: nagp-namespace
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS nagp;
    USE nagp;
    CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    GRANT ALL ON nagp.* TO 'root'@'%';
    FLUSH PRIVILEGES;
